apiVersion: v1
kind: Service
metadata:
  name: {{ include "healthcheckservice.fullname" . }}
  labels:
    {{- include "healthcheckservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if eq .Values.service.healthPort .Values.service.metricsPort }}
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
    - port: {{ .Values.service.metricsPort }}
      targetPort: health
      protocol: TCP
      name: metrics
    {{- else }}
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "healthcheckservice.selectorLabels" . | nindent 4 }}
